# Generated by Django 3.2.15 on 2022-08-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productReceipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_no',
            name='currency_format',
            field=models.CharField(choices=[('N', 'N'), ('$', '$'), ('EURO', 'EURO')], default='N', max_length=10),
            preserve_default=False,
        ),
    ]
