# Generated by Django 3.2.15 on 2022-08-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceReceipt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_qty',
            new_name='item_price',
        ),
    ]
