# Generated by Django 3.2.15 on 2023-05-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceReceipt', '0003_receipt_no_currency_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_no',
            name='currency_format',
            field=models.CharField(choices=[('₦', '₦'), ('$', '$'), ('£', '£'), ('€', '€'), ('¥', '¥'), ('₱', '₱'), ('₹', '₹'), ('R', 'R'), ('₽', '₽')], max_length=10),
        ),
    ]
