# Generated by Django 3.2.15 on 2022-08-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='business_logo',
            field=models.ImageField(null=True, upload_to='logo/'),
        ),
    ]
