# Generated by Django 3.2.15 on 2023-05-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_useraccount_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
